In [1]:
import matplotlib.pyplot as plt

In [10]:
import Initiate_Alignment.InitAlign as IA
import txtgrid_master.TextGrid_Master as txtgrd
from importlib import reload
import numpy as np
import mysql.connector
reload(IA)

<module 'Initiate_Alignment.InitAlign' from '/media/Windows/root/AusKidTalk/Initiate_Aligner/AusKidTalk/Initiate_Alignment/InitAlign.py'>

In [6]:
from collections import namedtuple, defaultdict
import pandas as pd
import numpy as np
import wave, struct
import logging
from os.path import isfile
import pyAudioAnalysis.pyAudioAnalysis.ShortTermFeatures as sF
reload(sF)
logger = logging.getLogger()
logger.setLevel(logging.INFO)

In [4]:
reload(IA)
import cProfile
cProfile.run("beeps = IA.GetBeepTimesML('beep.ini','../../Recordings/13_aug_2020/90 3_2_0/90 Primary_15-01.wav')")

std.py:145(__init__)
        2    0.000    0.000    0.000    0.000 std.py:154(__format__)
        2    0.000    0.000    0.000    0.000 std.py:227(format_interval)
        1    0.000    0.000    0.000    0.000 std.py:287(status_printer)
        2    0.000    0.000    0.006    0.003 std.py:297(fp_write)
        2    0.000    0.000    0.006    0.003 std.py:303(print_status)
        2    0.000    0.000    0.000    0.000 std.py:310(format_meter)
        1    0.000    0.000    0.002    0.002 std.py:511(__new__)
        1    0.000    0.000    0.000    0.000 std.py:533(_get_free_pos)
        1    0.000    0.000    0.000    0.000 std.py:536(<genexpr>)
        1    0.000    0.000    0.000    0.000 std.py:540(_decr_instances)
        1    0.000    0.000    0.001    0.001 std.py:623(get_lock)
        1    0.000    0.000    0.001    0.001 std.py:79(__init__)
        1    0.000    0.000    0.005    0.005 std.py:797(__init__)
        1    0.000    0.000    0.000    0.000 std.py:85(<listcomp>)
      

AttributeError: 'SVC' object has no attribute 'break_ties'

In [8]:
import time
from tqdm import tqdm

In [9]:
for i in tqdm(range(10)):
    time.sleep(0.1)

100%|██████████| 10/10 [00:01<00:00,  9.74it/s]


In [3]:
beeps = np.asarray([ 10345,50205,122302,221755,268294])

In [4]:
beeps = beeps/100

In [5]:
beeps

array([ 103.45,  502.05, 1223.02, 2217.55, 2682.94])

In [17]:
(beeps[1] - beeps[0])/60

6.6433333333333335

In [337]:
results = [{'Tables_in_auskidstalk': 'SESSION_PROGRESS'}, {'Tables_in_auskidstalk': 'Version_history'}, {'Tables_in_auskidstalk': 'child'}, {'Tables_in_auskidstalk': 'experiment'}, {'Tables_in_auskidstalk': 'location'}, {'Tables_in_auskidstalk': 'minigames_data'}, {'Tables_in_auskidstalk': 'ra'}, {'Tables_in_auskidstalk': 'review_questions_list'}, {'Tables_in_auskidstalk': 'task1'}, {'Tables_in_auskidstalk': 'task2_random_sequence'}, {'Tables_in_auskidstalk': 'task_start_end_times'}, {'Tables_in_auskidstalk': 'tasks_data'}, {'Tables_in_auskidstalk': 'words'}]
lTableNames = [list(i.values())[0] for i in results]

In [338]:
lTableNames[0]

'SESSION_PROGRESS'

In [24]:
reload(IA)
(tTasks, dTaskPrompts) = IA.ParseTStampCSV('../../Recordings/13_aug_2020/experiment.csv','../../Recordings/13_aug_2020/task_start_end_times.csv',90,'../../Recordings/words.csv')
(tTasks_2, dTaskPrompts_2) = IA.GetTimeStampsSQL(90)

[{'Tables_in_auskidstalk': 'SESSION_PROGRESS'}, {'Tables_in_auskidstalk': 'Version_history'}, {'Tables_in_auskidstalk': 'child'}, {'Tables_in_auskidstalk': 'experiment'}, {'Tables_in_auskidstalk': 'location'}, {'Tables_in_auskidstalk': 'minigames_data'}, {'Tables_in_auskidstalk': 'ra'}, {'Tables_in_auskidstalk': 'review_questions_list'}, {'Tables_in_auskidstalk': 'task1'}, {'Tables_in_auskidstalk': 'task2_random_sequence'}, {'Tables_in_auskidstalk': 'task_start_end_times'}, {'Tables_in_auskidstalk': 'tasks_data'}, {'Tables_in_auskidstalk': 'words'}]


2020-08-13 11:16:48.721000 2020-08-13 11:33:06.373000 1
2020-08-13 11:35:27.912000 2020-08-13 11:42:48.252000 2
2020-08-13 11:47:15.666000 2020-08-13 11:50:52.608000 3
2020-08-13 11:52:02.604000 2020-08-13 11:59:16.705000 4
2020-08-13 11:59:47.997000 NaT 5


In [25]:
tTasks_2

TaskTimes(task1=(0.0, 977.6519999504089), task2=(1119.1909999847412, 1559.531000137329), task3=(1826.9449999332428, 2043.8870000839233), task4=(2113.8830001354218, 2547.983999967575), task5=(2579.276000022888, -1))

In [26]:
tTasks

TaskTimes(task1=(0.0, 977.6519999504089), task2=(1119.1909999847412, 1559.531000137329), task3=(1826.9449999332428, 2043.8870000839233), task4=(2113.8830001354218, 2547.983999967575), task5=(2579.276000022888, -1))

In [27]:
dTaskPrompts

defaultdict(list,
            {1: [Prompt(taskID=1, wordID=2, word='fish', answerTime=111.3840000629425, cueOnset=54.680999994277954, cueOffset=77.4520001411438),
              Prompt(taskID=1, wordID=3, word='car', answerTime=123.60000014305115, cueOnset=111.39400005340576, cueOffset=111.42600011825562),
              Prompt(taskID=1, wordID=4, word='key', answerTime=128.6119999885559, cueOnset=123.61800003051758, cueOffset=123.6560001373291),
              Prompt(taskID=1, wordID=5, word='boat', answerTime=132.53900003433228, cueOnset=128.62700009346008, cueOffset=128.68300008773804),
              Prompt(taskID=1, wordID=6, word='snake', answerTime=147.42600011825562, cueOnset=132.5460000038147, cueOffset=132.5699999332428),
              Prompt(taskID=1, wordID=7, word='cow', answerTime=150.67400002479553, cueOnset=147.44200015068054, cueOffset=147.48800015449524),
              Prompt(taskID=1, wordID=8, word='frog', answerTime=153.3619999885559, cueOnset=150.68300008773804, cueOf

In [23]:
dTaskPrompts_2

defaultdict(list,
            {1: [Prompt(taskID=1, wordID=2, word='car', answerTime=111.3840000629425, cueOnset=54.680999994277954, cueOffset=77.4520001411438),
              Prompt(taskID=1, wordID=3, word='key', answerTime=123.60000014305115, cueOnset=111.39400005340576, cueOffset=111.42600011825562),
              Prompt(taskID=1, wordID=4, word='boat', answerTime=128.6119999885559, cueOnset=123.61800003051758, cueOffset=123.6560001373291),
              Prompt(taskID=1, wordID=5, word='snake', answerTime=132.53900003433228, cueOnset=128.62700009346008, cueOffset=128.68300008773804),
              Prompt(taskID=1, wordID=6, word='cow', answerTime=147.42600011825562, cueOnset=132.5460000038147, cueOffset=132.5699999332428),
              Prompt(taskID=1, wordID=7, word='frog', answerTime=150.67400002479553, cueOnset=147.44200015068054, cueOffset=147.48800015449524),
              Prompt(taskID=1, wordID=8, word='pig', answerTime=153.3619999885559, cueOnset=150.68300008773804, cueOff

In [401]:
dTaskPrompts[1][0]

Prompt(taskID=1, wordID=2, word='fish', answerTime=111.3840000629425, cueOnset=54.680999994277954, cueOffset=77.4520001411438)

In [410]:
for p in dTaskPrompts_2[1]:
    assert p.answerTime > p.cueOffset
    assert p.cueOffset > p.cueOnset

In [39]:
pdTasks = pd.read_csv('../../Recordings/13_aug_2020/task_start_end_times.csv',parse_dates=list(range(2,12)))

In [45]:
reload(IA)
testWav = '../../Recordings/13_aug_2020/90 3_2_0/90 Primary_15-01.wav'
IA.Segmentor('beep.ini',testWav,90,'out_2')

INFO:root:Child 90: Start Processing File ../../Recordings/13_aug_2020/90 3_2_0/90 Primary_15-01.wav
INFO:root:Child 90: Getting timestamps
INFO:root:Child 90: 5 tasks timestamps detected
INFO:root:Child 90: task 1 contains 130 prompts
INFO:root:Child 90: task 2 contains 36 prompts
INFO:root:Child 90: task 3 contains 13 prompts
INFO:root:Child 90: task 4 contains 2 prompts
INFO:root:Child 90: task 5 contains 39 prompts
INFO:root:Child 90: Getting Beep times
INFO:root:Child 90: offset time 103.59366661389676


[{'Tables_in_auskidstalk': 'SESSION_PROGRESS'}, {'Tables_in_auskidstalk': 'Version_history'}, {'Tables_in_auskidstalk': 'child'}, {'Tables_in_auskidstalk': 'experiment'}, {'Tables_in_auskidstalk': 'location'}, {'Tables_in_auskidstalk': 'minigames_data'}, {'Tables_in_auskidstalk': 'ra'}, {'Tables_in_auskidstalk': 'review_questions_list'}, {'Tables_in_auskidstalk': 'task1'}, {'Tables_in_auskidstalk': 'task2_random_sequence'}, {'Tables_in_auskidstalk': 'task_start_end_times'}, {'Tables_in_auskidstalk': 'tasks_data'}, {'Tables_in_auskidstalk': 'words'}]
2020-08-13 11:16:48.721000 2020-08-13 11:33:06.373000 1
2020-08-13 11:35:27.912000 2020-08-13 11:42:48.252000 2
2020-08-13 11:47:15.666000 2020-08-13 11:50:52.608000 3
2020-08-13 11:52:02.604000 2020-08-13 11:59:16.705000 4
2020-08-13 11:59:47.997000 NaT 5


INFO:root:Child 90: Annotating task 1
INFO:root:Child 90: Annotating task 2
INFO:root:Child 90: Annotating task 3
INFO:root:Child 90: Annotating task 4
INFO:root:Child 90: Annotating task 5


In [31]:
dTiers = {'Prompt': [[66.06650006771088, 111.41000008583069, 123.63700008392334, 128.65500009059906, 132.55799996852875, 147.4650001525879, 150.7115000486374, 153.3860000371933, 155.9135000705719, 159.0240000486374, 161.6434999704361, 164.74849998950958, 167.5055000782013, 170.3255000114441, 178.98200011253357, 188.9190000295639, 202.77050006389618, 206.3805000782013, 210.11450004577637, 213.75849997997284, 217.0, 220.3475000858307, 223.56149995326996, 226.21250009536743, 228.80599999427795, 232.86350011825562, 235.47100007534027, 238.07950007915497, 240.58050000667572, 243.0970001220703, 245.39750003814697, 248.34150004386902, 258.77500009536743, 274.1599999666214, 281.4645000696182, 286.3009999990463, 291.3310000896454, 295.1215000152588, 298.6455000638962, 302.24550008773804, 321.6065000295639, 326.4940000772476, 336.409500002861, 340.9580000638962, 347.23950004577637, 353.3914999961853, 453.38100004196167, 357.90350008010864, 362.00450003147125, 365.86650002002716, 400.71249997615814, 404.50300002098083, 408.9725000858307, 413.6909999847412, 418.5715000629425, 428.0590000152588, 432.3330000638962, 436.50650000572205, 441.1365000009537, 477.994500041008, 488.24000000953674, 493.77650010585785, 502.25099992752075, 505.1454999446869, 507.9780000448227, 511.1080000400543, 513.9474999904633, 516.869500041008, 519.1640001535416, 527.3995000123978, 530.449499964714, 532.9270000457764, 535.3570001125336, 538.1740000247955, 541.6310000419617, 551.9555000066757, 556.8500000238419, 559.8940000534058, 562.6005001068115, 566.2604999542236, 575.1325000524521, 579.9305000305176, 588.2920000553131, 591.9594999551773, 594.7750000953674, 598.4270000457764, 602.0770000219345, 605.2175000905991, 607.9205000400543, 610.93850004673, 616.6560001373291, 632.7540000677109, 637.3925000429153, 643.0105000734329, 648.4279999732971, 653.4869999885559, 657.8530000448227, 662.5995000600815, 666.81350004673, 671.2664999961853, 676.0675001144409, 680.2765001058578, 683.9724999666214, 693.1090000867844, 698.6230000257492, 704.5760000944138, 710.7065000534058, 715.7569999694824, 719.893000125885, 725.6695001125336, 730.0875000953674, 734.5095000267029, 739.4760000705719, 745.2475000619888, 750.0485000610352, 753.4280000925064, 757.8289999961853, 763.2305001020432, 785.5400000810623, 796.1154999732971, 801.8520001173019, 805.9264999628067, 809.9450000524521, 821.1449999809265, 875.2094999551773, 929.018000125885, 956.9045000076294, 965.2625000476837, 969.2260000705719, 973.4025000333786], [111.3840000629425, 123.60000014305115, 128.6119999885559, 132.53900003433228, 147.42600011825562, 150.67400002479553, 153.3619999885559, 155.86700010299683, 159.00200009346008, 161.614000082016, 164.7220001220703, 167.48099994659424, 170.2920000553131, 178.95300006866455, 188.89400005340576, 202.75200009346008, 206.3529999256134, 210.0900001525879, 213.73399996757507, 216.97099995613098, 220.3180000782013, 223.53999996185303, 226.18499994277954, 228.78400015830994, 232.8420000076294, 235.44799995422363, 238.05999994277954, 240.56100010871887, 243.07400012016296, 245.37599992752075, 248.31299996376038, 258.74399995803833, 272.17199993133545, 280.1579999923706, 285.1760001182556, 290.3989999294281, 294.1619999408722, 297.6949999332428, 301.29900002479553, 319.6360001564026, 325.58899998664856, 335.3159999847412, 339.79900002479553, 344.6010000705719, 352.1380000114441, 356.6210000514984, 476.69000005722046, 361.00999999046326, 365.07800006866455, 368.73099994659424, 403.65700006484985, 407.268000125885, 412.71200013160706, 416.7630000114441, 426.80200004577637, 431.0880000591278, 435.1619999408722, 439.75999999046326, 445.0770001411438, 488.21600008010864, 493.7550001144409, 502.22300004959106, 505.12400007247925, 507.9539999961853, 511.08899998664856, 513.9210000038147, 516.8470001220703, 519.1410000324249, 527.3789999485016, 530.4190001487732, 532.9060001373291, 535.3289999961853, 538.1510000228882, 541.6040000915527, 551.930999994278, 556.8280000686646, 559.8680000305176, 562.5829999446869, 566.2369999885559, 575.1119999885559, 579.9130001068115, 588.2710001468658, 591.9349999427795, 594.7539999485016, 597.7070000171661, 601.2300000190735, 604.3659999370575, 607.0859999656677, 609.8140001296997, 613.1879999637604, 621.1730000972748, 636.5210001468658, 640.6330001354218, 647.5940001010895, 651.989000082016, 656.8980000019073, 661.587000131607, 665.8970000743866, 669.9500000476837, 674.7509999275208, 679.1549999713898, 682.5950000286102, 692.0060000419617, 697.114000082016, 702.9650001525879, 709.4300000667572, 714.3600001335144, 718.8519999980927, 724.5859999656677, 728.7690000534058, 733.3740000724792, 737.6360001564026, 743.4010000228882, 748.8120000362396, 752.5599999427795, 756.7599999904633, 761.875, 784.420000076294, 794.9820001125336, 800.7300000190735, 804.8099999427795, 808.7620000839233, 814.7430000305176, 859.9670000076294, 914.289999961853, 955.779000043869, 960.9160001277924, 968.1219999790192, 972.2969999313354, 977.6579999923706], ['car', 'key', 'boat', 'snake', 'cow', 'frog', 'pig', 'giraffe', 'elephant', 'butterfly', 'crab', 'dinosaur', 'grasshopper', 'spiderweb', 'hippopotamus', 'tooth', 'Beard', 'Bellybutton', 'watch', 'straw', 'chair', 'leaf', 'cloud', 'mountain', 'shell', 'bag', 'swing', 'sword', 'wheel', 'yoyo', 'garden', 'skirt', 'that', 'zoo', 'cub', 'mouth', 'head', 'thumb', 'Moustache', 'voice', 'jam', 'food', 'dessert', 'tonight', 'kitchen', 'carpet', 'carpet', 'machine', 'girl', 'balloon', 'card', 'Circus', 'Doll', 'martian', 'No', 'yes', 'Ride', 'story', 'attack', 'cheese', 'banana', 'watermelon', 'coconut', 'cucumber', 'potato', 'tomato', 'vegemite', 'bird', 'feather', 'owl', 'gorilla', 'kangaroo', 'crocodile', 'ciacada', 'caterpillar', 'rhinoceros', 'clown', 'stethoscope', 'flowerpot', 'spade', 'treasure', 'canoe', 'bridge', 'xylophone', 'boy', 'hair', 'ear', 'nose', 'foot', 'short', 'play', 'ball', 'pull', 'pool', 'drink', 'Pie', 'sausage', 'spaghetti', 'vanilla', 'cart', 'tail', 'fur', 'detective', 'magician', 'breathe', 'garage', 'light', 'thermometer', 'hole', 'sprout', 'hill', 'smile', 'splash', 'wood', 'binoculars', 'Australia', 'Count eggs in grass', 'One cup', 'Two cups', 'Three cups', 'Four cups', 'One egg', 'Two eggs in cups', 'Three eggs in cups', 'Four eggs in cups', 'One o clock', 'Two o clock', 'Three o clock', 'Four o clock', 'Cats often catch mice']]}

In [32]:
for p in dTiers:
    lSTs, lETs, lLabls = dTiers[p]
    aSTs = np.asarray(lSTs)
    aETs = np.asarray(lETs)
    aLabels = np.asarray(lLabls)
    
    indxSort = np.argsort(aSTs)
    
    dTiers[p] = (aSTs[indxSort], aETs[indxSort],aLabels[indxSort])

In [46]:
aSTs[indxSort]

array([ 66.06650007, 111.41000009, 123.63700008, 128.65500009,
       132.55799997, 147.46500015, 150.71150005, 153.38600004,
       155.91350007, 159.02400005, 161.64349997, 164.74849999,
       167.50550008, 170.32550001, 178.98200011, 188.91900003,
       202.77050006, 206.38050008, 210.11450005, 213.75849998,
       217.        , 220.34750009, 223.56149995, 226.2125001 ,
       228.80599999, 232.86350012, 235.47100008, 238.07950008,
       240.58050001, 243.09700012, 245.39750004, 248.34150004,
       258.7750001 , 274.15999997, 281.46450007, 286.301     ,
       291.33100009, 295.12150002, 298.64550006, 302.24550009,
       321.60650003, 326.49400008, 336.4095    , 340.95800006,
       347.23950005, 353.3915    , 357.90350008, 362.00450003,
       365.86650002, 400.71249998, 404.50300002, 408.97250009,
       413.69099998, 418.57150006, 428.05900002, 432.33300006,
       436.50650001, 441.1365    , 453.38100004, 477.99450004,
       488.24000001, 493.77650011, 502.25099993, 505.14

In [40]:
lSTs, lETs, lLabls = dTiers['Prompt']
aSTs = np.asarray(lSTs)
aETs = np.asarray(lETs)
lLabls[93]
aSTs[93]
aETs[93]
i = 46
print(lLabls[i],aSTs[i],aETs[i])

carpet 453.38100004196167 476.69000005722046


In [42]:
RefTime = pdTasks.iloc[0].task1_start_time.timestamp()

In [43]:
RefTime

1597317408.721

In [44]:
answerTime = pdTask.iloc[0].answer_time

In [45]:
answerTime.timestamp() - RefTime

111.3840000629425

In [49]:
cueOnset = pdTask.iloc[0].audio_cue_onset

In [47]:
cueOnset = cueOnset.timestamp() - RefTime

In [50]:
cueOnset

Timestamp('2020-08-13 11:17:43.402000')

In [52]:
103+111

214

In [9]:
#Get number of tasks
nTasks = len(tTasks)
nBeepTimeStamps = []
for fTaskST, fTaskET in tTasks:
    nBeepTimeStamps.append(fTaskST) if fTaskST != -1 else Null
lDifTimes = []
for i in range(len(beeps)):
    for j in range(len(nBeepTimeStamps)):
        #print(i,j,beeps[i]-nBeepTimeStamps[j])
        lDifTimes.append(abs(beeps[i]-nBeepTimeStamps[j]))

lDifTimes = np.asarray(lDifTimes)
lDifTimes.sort()

iEqualDiss = np.where(np.diff(lDifTimes,n=1,axis=0) < 1 )[0]

if iEqualDiss.size == 0:
    print('Failed to verify beep times')
    offset=-1
else:
    offset = np.mean(lDifTimes[iEqualDiss])
print(offset)

103.59366661389676


In [10]:
iEqualDiss

array([0, 1, 2])

In [11]:
nBeepTimeStamps

[0.0,
 1119.1909999847412,
 1826.9449999332428,
 2113.8830001354218,
 2579.276000022888]

In [59]:
beeps = np.asarray([1033.45,2017.55, 2882.94])

In [29]:
res = []
for i in range(len(beeps)):
    for j in range(len(nBeepTimeStamps)):
        print(i,j,beeps[i]-nBeepTimeStamps[j])
        res.append(beeps[i]-nBeepTimeStamps[j])

0 0 103.45
0 1 -1015.7409999847412
0 2 -1723.4949999332428
0 3 -2010.4330001354217
0 4 -2475.8260000228884
1 0 502.05
1 1 -617.1409999847413
1 2 -1324.8949999332428
1 3 -1611.8330001354218
1 4 -2077.226000022888
2 0 1223.02
2 1 103.82900001525877
2 2 -603.9249999332428
2 3 -890.8630001354218
2 4 -1356.2560000228882
3 0 2217.55
3 1 1098.359000015259
3 2 390.6050000667574
3 3 103.66699986457843
3 4 -361.726000022888
4 0 2682.94
4 1 1563.7490000152588
4 2 855.9950000667573
4 3 569.0569998645783
4 4 103.66399997711187


In [47]:
np.mean(res[np.where(abs(np.diff(res,n=1))<1)])

103.59366661389676

In [44]:
res = np.asarray(res)

In [12]:
offset = IA.GetOffsetTime(tTasks,beeps)

In [74]:
dTaskPrompts

defaultdict(list,
            {1: [Prompt(taskID=1, wordID=2, word='fish', answerTime=111.3840000629425, cueOnset=54.680999994277954, cueOffset=77.4520001411438),
              Prompt(taskID=1, wordID=3, word='car', answerTime=123.60000014305115, cueOnset=111.39400005340576, cueOffset=111.42600011825562),
              Prompt(taskID=1, wordID=4, word='key', answerTime=128.6119999885559, cueOnset=123.61800003051758, cueOffset=123.6560001373291),
              Prompt(taskID=1, wordID=5, word='boat', answerTime=132.53900003433228, cueOnset=128.62700009346008, cueOffset=128.68300008773804),
              Prompt(taskID=1, wordID=6, word='snake', answerTime=147.42600011825562, cueOnset=132.5460000038147, cueOffset=132.5699999332428),
              Prompt(taskID=1, wordID=7, word='cow', answerTime=150.67400002479553, cueOnset=147.44200015068054, cueOffset=147.48800015449524),
              Prompt(taskID=1, wordID=8, word='frog', answerTime=153.3619999885559, cueOnset=150.68300008773804, cueOf

In [15]:
testWav = '../../Recordings/13_aug_2020/90 3_2_0/90 Primary_15-01.wav'
_wav_param, RWav = txtgrd.ReadWavFile(testWav)
nTasks = len(tTasks)
for i in range(nTasks):
    fTaskST,fTaskET = tTasks[i]
    print(fTaskST,fTaskET,i)
    #Fix missing start and end times of tasks, if start missing use end of previous task, if end time missing use start time of next task
    if fTaskST == -1:
        if i ==0:
            fTaskST = 0
        else:
            fTaskST = tTasks[i-1][1]
    if fTaskET == -1:
        if i == nTasks -1:
            fTaskET = _wav_param.nframes/_wav_param.framerate
        else:
            fTaskET = tTasks[i+1][0]
    fTaskST += offset
    fTaskET += offset
    
    fTaskSF = int(fTaskST*_wav_param.framerate*_wav_param.sampwidth)
    fTaskEF = int(fTaskET*_wav_param.framerate*_wav_param.sampwidth)
    fTaskSF += (fTaskSF%2)
    fTaskEF += (fTaskEF%2)
    print(fTaskSF, fTaskEF,fTaskST,fTaskET)
    nFrams = int((fTaskEF-fTaskSF)/_wav_param.sampwidth)
    txtgrd.WriteWaveSegment(RWav[fTaskSF:fTaskEF],_wav_param,nFrams,'task{}.wav'.format(i))
            

0.0 977.6519999504089 0
9136962 95365868 103.59366661389676 1081.2456665643058
1119.1909999847412 1559.531000137329 1
107849608 146687596 1222.784666598638 1663.124666751226
1826.9449999332428 2043.8870000839233 2
170273510 189407794 1930.5386665471397 2147.48066669782
2113.8830001354218 2547.983999967575 3
195581442 233869150 2217.4766667493186 2651.577666581472
2579.276000022888 -1 4
236629104 275906360 2682.869666636785 3128.190015820246


In [2]:
import logging

In [3]:
logging.Logger.setLevel(logging.INFO)

TypeError: setLevel() missing 1 required positional argument: 'level'

In [33]:
logger = logging.getLogger()

In [34]:
logger.setLevel(logging.INFO)

In [48]:
from os.path import splitext, basename

In [49]:
splitext(basename(testWav))[0]

'90 Primary_15-01'

In [54]:
dTiers = defaultdict(lambda: [[],[],[]])

In [53]:
from collections import defaultdict

In [55]:
offset

103.59366661389676

In [68]:
lST = [t.cueOffset for t in dTaskPrompts[1]]
lET = [t.answerTime for t in dTaskPrompts[1]]
lLabels = [t.word for t in dTaskPrompts[1]]
dTiers['Prompt']=[lST,lET,lLabels]

In [59]:
labels

['fish',
 'car',
 'key',
 'boat',
 'snake',
 'cow',
 'frog',
 'pig',
 'giraffe',
 'elephant',
 'butterfly',
 'crab',
 'dinosaur',
 'grasshopper',
 'spiderweb',
 'hippopotamus',
 'tooth',
 'Beard',
 'Bellybutton',
 'watch',
 'straw',
 'chair',
 'leaf',
 'cloud',
 'mountain',
 'shell',
 'bag',
 'swing',
 'sword',
 'wheel',
 'yoyo',
 'garden',
 'skirt',
 'that',
 'zoo',
 'cub',
 'mouth',
 'head',
 'thumb',
 'Moustache',
 'voice',
 'jam',
 'food',
 'dessert',
 'tonight',
 'kitchen',
 'carpet',
 'machine',
 'girl',
 'balloon',
 'card',
 'Circus',
 'Doll',
 'martian',
 'No',
 'yes',
 'Ride',
 'story',
 'kitchen',
 'attack',
 'cheese',
 'banana',
 'watermelon',
 'coconut',
 'cucumber',
 'potato',
 'tomato',
 'vegemite',
 'bird',
 'feather',
 'owl',
 'gorilla',
 'kangaroo',
 'crocodile',
 'ciacada',
 'caterpillar',
 'rhinoceros',
 'clown',
 'stethoscope',
 'flowerpot',
 'spade',
 'treasure',
 'canoe',
 'bridge',
 'xylophone',
 'boy',
 'hair',
 'ear',
 'nose',
 'foot',
 'short',
 'play',
 'ball

In [69]:
txtgrd.WriteTxtGrdFromDict('task1.txtgrid',dTiers,0.0,lET[-1])

In [64]:
lET

[214.97766667683925,
 227.1936667569479,
 232.20566660245265,
 236.13266664822902,
 251.01966673215236,
 254.26766663869228,
 256.95566660245265,
 259.46066671689357,
 262.5956667073568,
 265.20766669591274,
 268.31566673596706,
 271.074666560491,
 273.88566666920985,
 282.5466666825613,
 292.4876666673025,
 306.3456667073568,
 309.94666653951015,
 313.68366676648463,
 317.3276665814718,
 320.5646665700277,
 323.91166669209804,
 327.13366657574977,
 329.7786665566763,
 332.3776667722067,
 336.43566662152614,
 339.0416665681204,
 341.6536665566763,
 344.1546667226156,
 346.6676667340597,
 348.9696665414175,
 351.9066665776571,
 362.3376665719351,
 375.7656665452322,
 383.75166660626735,
 388.76966673215236,
 393.99266654332484,
 397.75566655476894,
 401.28866654713954,
 404.8926666386923,
 423.22966677029933,
 429.1826666005453,
 438.90966659863795,
 443.3926666386923,
 448.19466668446864,
 455.73166662534084,
 460.21466666539516,
 464.60366660436,
 468.6716666825613,
 472.324666560491,

In [65]:
lST

[181.04566675504054,
 215.01966673215236,
 227.24966675122585,
 232.27666670163478,
 236.16366654713954,
 251.08166676839198,
 254.3336666234335,
 256.99766665776576,
 259.53666669209804,
 262.632666648229,
 265.25866657574977,
 268.3626666673025,
 271.1146667607626,
 273.9366665490469,
 282.5956667073568,
 292.5296667226156,
 306.3796666272482,
 309.9916666158041,
 313.72566658337917,
 317.3706665643057,
 320.6166666158041,
 323.96066671689357,
 327.1696665891012,
 329.8256667264303,
 332.4156666405996,
 336.47366672833766,
 339.08266669591274,
 341.6876667149862,
 344.188666642507,
 346.70766669591274,
 349.007666648229,
 351.95566660245265,
 362.3956666596731,
 379.73866659482326,
 386.3586667188009,
 391.01466661771144,
 395.8516667493185,
 399.6656666405996,
 403.18366676648463,
 406.78066665013637,
 427.1656666405996,
 430.9876666673025,
 441.0836666234335,
 445.70566660245265,
 453.467666686376,
 458.2326665528616,
 462.77366668065395,
 466.58566671689357,
 470.2436667092642,
 5

In [70]:
dTiers.keys()

dict_keys(['Prompt'])

In [71]:
txtgrd.FillGapsInTxtGridDict(dTiers)

defaultdict(<function txtgrid_master.TextGrid_Master.FillGapsInTxtGridDict.<locals>.<lambda>()>,
            {'Prompt': [[77.4520001411438,
               111.3840000629425,
               111.42600011825562,
               123.60000014305115,
               123.6560001373291,
               128.6119999885559,
               128.68300008773804,
               132.53900003433228,
               132.5699999332428,
               147.42600011825562,
               147.48800015449524,
               150.67400002479553,
               150.74000000953674,
               153.3619999885559,
               153.40400004386902,
               155.86700010299683,
               155.9430000782013,
               159.00200009346008,
               159.03900003433228,
               161.614000082016,
               161.66499996185303,
               164.7220001220703,
               164.76900005340576,
               167.48099994659424,
               167.52100014686584,
               170.2920000553

In [82]:
import mysql.connector

In [76]:
server_name = '166.62.28.111'

In [77]:
database_name = 'auskidstalk'

In [376]:
try:
    conn = mysql.connector.connect(user='unsw', password='UNSWspeech',
                              host='166.62.28.111',
                              database='auskidstalk',buffered=True)
except Exception as err:
    print('MySQL connection failure with error \n{0}'.format(err))

In [27]:
try:
    conn = mysql.connector.connect(user='mostafa', password='Hggih;fv2881',
                              host='localhost',
                              database='auskidstalk',buffered=True)
except Exception as err:
    print('MySQL connection failure with error \n{0}'.format(err))

In [28]:
cursor = conn.cursor(buffered=True, dictionary=True)

In [231]:
conn.connect()

In [367]:
#query = ("SELECT * FROM task_start_end_times WHERE child_id=90")
query = ("SELECT * FROM experiment WHERE id=90")
#query = ("SHOW TABLES LIKE 'ff'")# LIKE 'task_start_end_times'")

In [370]:
cursor.execute(query)

In [371]:
d = cursor.fetchall()

In [235]:
import pandas as pd

In [372]:
pdata = pd.DataFrame.from_dict(d)

In [375]:
pdata.head()

Empty DataFrame
Columns: []
Index: []

In [357]:
d

[{'child_id': 90,
  'ra_id': 7,
  'task1_start_time': '2020/08/13 11:23:27.321',
  'task1_end_time': '2020/08/13 11:33:06.373',
  'task1_start_time_2': '',
  'task1_end_time_2': '',
  'task2_start_time': '2020/08/13 11:35:27.912',
  'task2_end_time': '2020/08/13 11:42:48.252',
  'task3_start_time': '2020/08/13 11:47:15.666',
  'task3_end_time': '2020/08/13 11:50:52.608',
  'task4_start_time': '2020/08/13 11:52:02.604',
  'task4_end_time': '2020/08/13 11:59:16.705',
  'task5_start_time': '2020/08/13 11:59:47.997',
  'task5_end_time': ''}]

In [257]:
len(d)

0

In [362]:
pdata.task1_start_time[0].timestamp()

1597317807.321

In [361]:
pdata['task1_start_time'] = pd.to_datetime(pdata['task1_start_time'])

In [287]:
pdata.task4_audio_cue_offset[0]

NaT

In [296]:
x = pdata.iloc[0]

In [322]:
x

id                                                      90
task_id                                                  1
word_id                                                  1
answer_value                                             1
answer_time                        2020-08-13 11:17:43.388
task1_attempt_count                                      0
task1_audio_cue_offset          2020-08-13 11:17:19.153000
audio_cue_onset                    2020-08-13 11:17:19.117
task2_sentence_offset                                     
task2_start_signal_time_used                             0
task2_child_starts_speaking                               
task3_time_spent_on_picture                              0
task4_button_tap_time                                     
task4_child_start_speaking                                
task4_audio_cue_offset                                 NaT
task1_retry1_timestamp                                 NaT
task1_retry2_timestamp                                  

In [321]:
x.task1_retry1_timestamp = pd.to_datetime(x.task1_retry1_timestamp)

/home/mostafa/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5303: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [320]:
pd.isnull(x.values[8])

False

In [313]:
type(x.task1_audio_cue_offset)

pandas._libs.tslibs.timestamps.Timestamp

In [323]:
x.loc['id':'audio_cue_onset']

id                                                90
task_id                                            1
word_id                                            1
answer_value                                       1
answer_time                  2020-08-13 11:17:43.388
task1_attempt_count                                0
task1_audio_cue_offset    2020-08-13 11:17:19.153000
audio_cue_onset              2020-08-13 11:17:19.117
Name: 0, dtype: object

In [14]:
try:
    conn = mysql.connector.connect(user='unsw', password='UNSWspeech',
                              host='166.62.28.111',
                              database='auskidstalk',buffered=True)
except Exception as err:
    print('MySQL connection failure with error \n{0}'.format(err))
cursor = conn.cursor(buffered=True, dictionary=True)
iChildID = 90
query = ("SELECT * FROM words") #WHERE child_id=90")
cursor.execute(query)
results = cursor.fetchall()


In [17]:
results

[{'word_id': 1, 'name': 'duck'},
 {'word_id': 2, 'name': 'fish'},
 {'word_id': 3, 'name': 'car'},
 {'word_id': 4, 'name': 'key'},
 {'word_id': 5, 'name': 'boat'},
 {'word_id': 6, 'name': 'snake'},
 {'word_id': 7, 'name': 'cow'},
 {'word_id': 8, 'name': 'frog'},
 {'word_id': 9, 'name': 'pig'},
 {'word_id': 10, 'name': 'giraffe'},
 {'word_id': 11, 'name': 'elephant'},
 {'word_id': 12, 'name': 'butterfly'},
 {'word_id': 13, 'name': 'crab'},
 {'word_id': 14, 'name': 'dinosaur'},
 {'word_id': 15, 'name': 'grasshopper'},
 {'word_id': 16, 'name': 'spiderweb'},
 {'word_id': 17, 'name': 'hippopotamus'},
 {'word_id': 18, 'name': 'tooth'},
 {'word_id': 19, 'name': 'Beard'},
 {'word_id': 20, 'name': 'Bellybutton'},
 {'word_id': 21, 'name': 'watch'},
 {'word_id': 22, 'name': 'straw'},
 {'word_id': 23, 'name': 'chair'},
 {'word_id': 24, 'name': 'leaf'},
 {'word_id': 25, 'name': 'cloud'},
 {'word_id': 26, 'name': 'mountain'},
 {'word_id': 27, 'name': 'shell'},
 {'word_id': 28, 'name': 'bag'},
 {'word

In [23]:
pdata = pd.DataFrame.from_dict(results).set_index('word_id')
#pdata = pdata.set_index('word_id')

In [24]:
pdata.head()

name
word_id      
1        duck
2        fish
3         car
4         key
5        boat

In [22]:
pdata.to_dict()['name']

{1: 'duck',
 2: 'fish',
 3: 'car',
 4: 'key',
 5: 'boat',
 6: 'snake',
 7: 'cow',
 8: 'frog',
 9: 'pig',
 10: 'giraffe',
 11: 'elephant',
 12: 'butterfly',
 13: 'crab',
 14: 'dinosaur',
 15: 'grasshopper',
 16: 'spiderweb',
 17: 'hippopotamus',
 18: 'tooth',
 19: 'Beard',
 20: 'Bellybutton',
 21: 'watch',
 22: 'straw',
 23: 'chair',
 24: 'leaf',
 25: 'cloud',
 26: 'mountain',
 27: 'shell',
 28: 'bag',
 29: 'swing',
 30: 'sword',
 31: 'wheel',
 32: 'yoyo',
 33: 'garden',
 34: 'skirt',
 35: 'that',
 36: 'zoo',
 37: 'cub',
 38: 'mouth',
 39: 'head',
 40: 'thumb',
 41: 'Moustache',
 42: 'voice',
 43: 'jam',
 44: 'food',
 45: 'dessert',
 46: 'tonight',
 47: 'kitchen',
 48: 'carpet',
 49: 'machine',
 50: 'girl',
 51: 'balloon',
 52: 'card',
 53: 'Circus',
 54: 'Doll',
 55: 'martian',
 56: 'No',
 57: 'yes',
 58: 'Ride',
 59: 'story',
 60: 'attack',
 61: 'cheese',
 62: 'banana',
 63: 'watermelon',
 64: 'coconut',
 65: 'cucumber',
 66: 'potato',
 67: 'tomato',
 68: 'vegemite',
 69: 'bird',
 70:

In [33]:
dTiers

{'Prompt': (array([ 66.06650007, 111.41000009, 123.63700008, 128.65500009,
         132.55799997, 147.46500015, 150.71150005, 153.38600004,
         155.91350007, 159.02400005, 161.64349997, 164.74849999,
         167.50550008, 170.32550001, 178.98200011, 188.91900003,
         202.77050006, 206.38050008, 210.11450005, 213.75849998,
         217.        , 220.34750009, 223.56149995, 226.2125001 ,
         228.80599999, 232.86350012, 235.47100008, 238.07950008,
         240.58050001, 243.09700012, 245.39750004, 248.34150004,
         258.7750001 , 274.15999997, 281.46450007, 286.301     ,
         291.33100009, 295.12150002, 298.64550006, 302.24550009,
         321.60650003, 326.49400008, 336.4095    , 340.95800006,
         347.23950005, 353.3915    , 357.90350008, 362.00450003,
         365.86650002, 400.71249998, 404.50300002, 408.97250009,
         413.69099998, 418.57150006, 428.05900002, 432.33300006,
         436.50650001, 441.1365    , 453.38100004, 477.99450004,
         488.24

In [42]:
with open('out_2/90 Primary_15-01_task1.int','w') as f:
    for fST, fET, sLabel in zip(*dTiers['Prompt']):
        print(fST, fET, sLabel, file=f)

In [38]:
x,y,z = dTiers['Prompt']

In [41]:
for m,n,o in zip(*dTiers['Prompt']):
    print(m,n,o)

66.06650006771088 111.3840000629425 car
111.41000008583069 123.60000014305115 key
123.63700008392334 128.6119999885559 boat
128.65500009059906 132.53900003433228 snake
132.55799996852875 147.42600011825562 cow
147.4650001525879 150.67400002479553 frog
150.7115000486374 153.3619999885559 pig
153.3860000371933 155.86700010299683 giraffe
155.9135000705719 159.00200009346008 elephant
159.0240000486374 161.614000082016 butterfly
161.6434999704361 164.7220001220703 crab
164.74849998950958 167.48099994659424 dinosaur
167.5055000782013 170.2920000553131 grasshopper
170.3255000114441 178.95300006866455 spiderweb
178.98200011253357 188.89400005340576 hippopotamus
188.9190000295639 202.75200009346008 tooth
202.77050006389618 206.3529999256134 Beard
206.3805000782013 210.0900001525879 Bellybutton
210.11450004577637 213.73399996757507 watch
213.75849997997284 216.97099995613098 straw
217.0 220.3180000782013 chair
220.3475000858307 223.53999996185303 leaf
223.56149995326996 226.18499994277954 cloud


In [17]:
beeps_122 = IA.GetBeepTimesML('beep.ini','../../Recordings/122/122.wav')

  0%|          | 0/449893 [38:24<?, ?it/s]


In [21]:
beeps_all = []
for i in ['130', '172', '173', '176', '177','197','216','218','220','222','237','243']:
    f = '../../Recordings/{}.wav'.format(i)
    print(f)
    beeps_all.append(IA.GetBeepTimesML('beep.ini',f))


../../Recordings/130.wav
  0%|          | 0/234676 [19:57<?, ?it/s]


In [10]:
clf = load('Model_7.jbl')

In [9]:
from joblib import dump, load

In [11]:
clf

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=10, break_ties=None, cache_size=200,
                     class_weight='balanced', coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma=0.0001,
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=None)

In [15]:
sv = clf['svc']

In [16]:
sv.

AttributeError: 'SVC' object has no attribute 'break_ties'

In [3]:
import sklearn

In [5]:
sklearn.__version__

'0.23.2'

In [7]:
beeps

array([], dtype=float64)

In [8]:
!ls

'=0.23'				       beep.ini		     out_2
'=0.23.1'			       egs		     pyAudioAnalysis
 auskidtalk_2.sql		       Extract_Pitch.praat   README.md
 auskidtalk_experiment.sql	       Initiate_Alignment    temp
 auskidtalk.sql			       Model_0.jbl	     Test_Aligner.ipynb
 auskidtalk_task_start_end_times.sql   Model_1.jbl	     txtgrid_master
 auskidtalk_words.sql		       oldModel
'Beep Detection Model.ipynb'	       out


In [18]:
beeps_122

array([  10.23,  644.65, 3283.61, 4095.36])

In [23]:
beeps_135 

array([  93.99,  629.79, 2161.85, 2979.61])

In [14]:
import copy

In [22]:
beeps_all

[array([  43.18,  515.06, 2231.09, 2736.61]),
 array([  21.12, 2194.41, 2788.68]),
 array([  68.54, 1148.85, 3853.18, 4345.5 , 5012.96]),
 array([ 473.19, 1259.77, 2299.72, 2716.24, 3101.69, 3506.36]),
 array([ 347.26, 1197.55, 3054.12, 4036.22, 4266.85, 5359.17]),
 array([ 979.84, 1989.12, 2289.26, 4551.48, 5151.84]),
 array([  81.77,  383.04,  905.1 , 1306.55, 1482.41, 1918.99]),
 array([  82.82,  441.38, 1778.9 , 2022.4 , 2597.73]),
 array([ 180.26,  662.14, 2288.77, 2667.73, 3212.9 ]),
 array([  41.93,  441.24, 2053.84, 2425.51, 2954.24]),
 array([   2.64,  184.95,  272.07,  472.62,  890.69, 1199.42, 1338.59,
        1634.51]),
 array([ 210.16,  442.77, 1428.41, 1618.53, 2109.7 ])]

In [5]:
beeps_122

In [29]:
reload(IA)
tTasks, dTaskPrompts = IA.GetTimeStampsSQL(122)

[{'Tables_in_auskidtalk_prod': 'SESSION_PROGRESS'}, {'Tables_in_auskidtalk_prod': 'Version_history'}, {'Tables_in_auskidtalk_prod': 'child'}, {'Tables_in_auskidtalk_prod': 'experiment'}, {'Tables_in_auskidtalk_prod': 'location'}, {'Tables_in_auskidtalk_prod': 'minigames_data'}, {'Tables_in_auskidtalk_prod': 'ra'}, {'Tables_in_auskidtalk_prod': 'review_questions_list'}, {'Tables_in_auskidtalk_prod': 'task1'}, {'Tables_in_auskidtalk_prod': 'task2_random_sequence'}, {'Tables_in_auskidtalk_prod': 'task_start_end_times'}, {'Tables_in_auskidtalk_prod': 'tasks_data'}, {'Tables_in_auskidtalk_prod': 'words'}]
2020-10-08 10:25:19.130000 2020-10-08 10:51:12.979000 1
2020-10-08 10:53:10.675000 2020-10-08 11:01:34.263000 2
2020-10-08 11:04:21.765000 2020-10-08 11:09:02.770000 3
2020-10-08 11:19:52.204000 2020-10-08 11:27:19.572000 4
2020-10-08 11:33:23.910000 2020-10-08 11:38:29.738000 5


In [30]:
tTasks

TaskTimes(task1=(0.0, 1553.8489999771118), task2=(1671.5449998378754, 2175.132999897003), task3=(2342.6349999904633, 2623.6399998664856), task4=(3273.0739998817444, 3720.441999912262), task5=(4084.7799999713898, 4390.607999801636))

## Steps

In [12]:
ChildID = 135
#TODO: Get the speech file
#TODO: Convert to 16 bit
#Get Beeps
#beeps = IA.GetBeepTimesML('beep.ini','../../Recordings/122.wav')
#beeps = beeps_122
#print('ChildID {0}: BeepDetection: {1} beeps detected @ times {2}'.format(ChildID,len(beeps),beeps))
tTasks, dTaskPrompts = IA.GetTimeStampsSQL(ChildID)

[{'Tables_in_auskidtalk_prod': 'SESSION_PROGRESS'}, {'Tables_in_auskidtalk_prod': 'Version_history'}, {'Tables_in_auskidtalk_prod': 'child'}, {'Tables_in_auskidtalk_prod': 'experiment'}, {'Tables_in_auskidtalk_prod': 'location'}, {'Tables_in_auskidtalk_prod': 'minigames_data'}, {'Tables_in_auskidtalk_prod': 'ra'}, {'Tables_in_auskidtalk_prod': 'review_questions_list'}, {'Tables_in_auskidtalk_prod': 'task1'}, {'Tables_in_auskidtalk_prod': 'task2_random_sequence'}, {'Tables_in_auskidtalk_prod': 'task_start_end_times'}, {'Tables_in_auskidtalk_prod': 'tasks_data'}, {'Tables_in_auskidtalk_prod': 'words'}]
2020-10-07 09:03:00.863000 2020-10-07 09:24:25.252000 1
2020-10-07 09:25:13.135000 2020-10-07 09:35:08.132000 2
2020-10-07 09:37:28.523000 2020-10-07 09:42:12.639000 3
2020-10-07 09:43:24.192000 2020-10-07 09:50:40.822000 4
2020-10-07 09:51:06.250000 2020-10-07 09:56:52.183000 5


In [42]:
reload(IA)
IA.Segmentor('beep.ini','../../Recordings/122.wav',122,'122')

[{'Tables_in_auskidtalk_prod': 'SESSION_PROGRESS'}, {'Tables_in_auskidtalk_prod': 'Version_history'}, {'Tables_in_auskidtalk_prod': 'child'}, {'Tables_in_auskidtalk_prod': 'experiment'}, {'Tables_in_auskidtalk_prod': 'location'}, {'Tables_in_auskidtalk_prod': 'minigames_data'}, {'Tables_in_auskidtalk_prod': 'ra'}, {'Tables_in_auskidtalk_prod': 'review_questions_list'}, {'Tables_in_auskidtalk_prod': 'task1'}, {'Tables_in_auskidtalk_prod': 'task2_random_sequence'}, {'Tables_in_auskidtalk_prod': 'task_start_end_times'}, {'Tables_in_auskidtalk_prod': 'tasks_data'}, {'Tables_in_auskidtalk_prod': 'words'}]
2020-10-08 10:25:19.130000 2020-10-08 10:51:12.979000 1
2020-10-08 10:53:10.675000 2020-10-08 11:01:34.263000 2
2020-10-08 11:04:21.765000 2020-10-08 11:09:02.770000 3
2020-10-08 11:19:52.204000 2020-10-08 11:27:19.572000 4
2020-10-08 11:33:23.910000 2020-10-08 11:38:29.738000 5


In [33]:
ls ../../Recordings/

 10_March_2020/   197.wav*       9_jan_2020/
 122/             216.wav*       Beep_Times_2.csv*
 122.wav*         218.wav*       Beep_Times.csv*
 130.wav*         220.wav*      'Individual Mics'/
 135.wav*         222.wav*      'Lab test 1-20191105T004956Z-001'/
 13_aug_2020/     237.wav*      'Lab test 1-20191105T004956Z-001.zip'*
 172.wav*         243.wav*      'Sample recordings-20191104T230038Z-001'/
 173.wav*         24_jan_2020/  'Sample recordings-20191104T230038Z-001.zip'*
 176.wav*         252.wav*       words.csv*
 177.wav*         28_jul_2020/


In [3]:
lBeepTimes = np.asarray([  10.23,  644.65, 3283.61, 4095.36])
#lBeepTimes = lBeepTimes / 100.0
IA.GetOffsetTime(tTasks,lBeepTimes)

NameError: name 'tTasks' is not defined

In [41]:
nTasks = len(tTasks)
nBeepTimeStamps = []
for fTaskST, fTaskET in tTasks:
    nBeepTimeStamps.append(fTaskST) if fTaskST != -1 else Null
lDifTimes = []
for i in range(len(lBeepTimes)):
    for j in range(len(nBeepTimeStamps)):
        lDifTimes.append(abs(lBeepTimes[i]-nBeepTimeStamps[j]))
lDifTimes = np.asarray(lDifTimes)
lDifTimes.sort()
iEqualDiss = np.where(np.diff(lDifTimes,n=1,axis=0) < 1 )[0]

In [43]:
dTaskPrompts

,
              Prompt(taskID=1, wordID=89, word='nose', answerTime=1095.1269998550415, cueOnset=1080.1889998912811, cueOffset=1081.8309998512268),
              Prompt(taskID=1, wordID=90, word='foot', answerTime=1101.0009999275208, cueOnset=1095.1289999485016, cueOffset=1097.3819999694824),
              Prompt(taskID=1, wordID=91, word='short', answerTime=1114.7649998664856, cueOnset=1101.0019998550415, cueOffset=1107.9619998931885),
              Prompt(taskID=1, wordID=92, word='play', answerTime=1133.6849999427795, cueOnset=1114.7669999599457, cueOffset=1130.6409997940063),
              Prompt(taskID=1, wordID=93, word='ball', answerTime=1138.385999917984, cueOnset=1133.686999797821, cueOffset=1135.4909999370575),
              Prompt(taskID=1, wordID=94, word='pull', answerTime=1145.898999929428, cueOnset=1138.3869998455048, cueOffset=1143.2599999904633),
              Prompt(taskID=1, wordID=95, word='pool', answerTime=1150.2709999084473, cueOnset=1145.901999950409, cueOffset=

In [8]:
pwd

'/media/Windows/root/AusKidTalk/Initiate_Aligner/AusKidTalk'

In [16]:
ls egs/Beeps

135_1_44_2ch.wav*  Sample2.wav*  Sample4.wav*  Sample6.wav*  Sample8.wav*
Sample1.wav*       Sample3.wav*  Sample5.wav*  Sample7.wav*  Sample9.wav*


In [22]:
reload(IA)
f = 'egs/Beeps/Sample1.wav'
IA.GetBeepTimesML('beep.ini',f)

INFO:InitAlign:Processing file egs/Beeps/Sample1.wav contains 3046 frames
100%|█████████▉| 3045/3046 [00:35<00:00, 85.80it/s]
INFO:InitAlign:File egs/Beeps/Sample1.wav: 1 beeps detected at [7.22]


array([7.22])